### PR TITLE
Fix Gnocchi CI

### PR DESCRIPTION
**Pull request by jd**
This uses Gnocchi docker image to run its tests easily.

### CODE REVIEW

**Comment by jd** [comment]
Fix YAML

**Comment by jd** [comment]
Fix env name

**Comment by jd** [comment]
Fix non-Gnocchi targets

**Comment by jd** [comment]
@cdent that should be solved :)

**Comment by cdent** [comment]
I'll go ahead and merge this, but will hold off on making the gnocchi target failing until gnocchi is fixed.

**Pull request merged**
